### ISSUE TITLE
Allowing to import any PR

### ISSUE THREAD

**Issue by apcros** [apcros/Inspicio#19]
As mentionned by @keithbro , currently Inspicio doesn't let you import a Pull request to a repo you don't own. 
(For example if you forked a repo and you then made a pull request to the original repo, Inspicio won't show it under your fork )

**Comment by apcros** [comment]
^^ this is being worked on https://github.com/apcros/Inspicio/tree/import_forked_prs

**Comment by apcros** [comment]
#22 < This is now in review @keithbro

**Comment by apcros** [comment]
This feature is now live, let me know if you're happy with it @keithbro and I'll close this issue.

**Comment by keithbro** [comment]
Hey it works, thank you! - however I can now see all PRs for the original repo, not just the ones I created. It doesn't really matter but would probably be better if I could just see my own.

Couple of other unrelated things (I can create new issues if you like):

* I can't edit the description of the code review in Inspicio after it's created
* It's a bit annoying to have to enter a title in Inspicio when Github already has one for the PR

**Comment by apcros** [comment]
Awesome ! 
Yes the pull request was done on purpose, just in case you want to put up someone else PR to which you contributed ? Let's see later if I'll change it

Description edition is a known thing and I need to take care of it, I'll create an issue. 

Feel free to create an issue for the title auto population, should be easy enough to add

**Comment by keithbro** [comment]
👍🏼   thanks mate!!
