### ISSUE TITLE
Auto-populate Review title from Github title (and Bitbucket?)

### ISSUE THREAD

**Issue by keithbro** [apcros/Inspicio#24]
It would be very nice to auto populate the review title from Github data, perhaps it could be:

"$project_name - $pull_request_title"

e.g.

"Inspicio - Allow to import PR from forked repos"

"Ramda - `path` and `assocPath` to support negative indexes"

**Comment by apcros** [comment]
Should be easy enough as everything is done Async. 
The same way the "PR" dropdown reload when you change the repo, I can change the title when you select a PR

**Comment by apcros** [comment]
This is now in review https://github.com/apcros/Inspicio/pull/25

**Comment by apcros** [comment]
This is now live. As usual, let me know if you're happy and I'll close the issue

**Comment by keithbro** [comment]
Looks good, thanks mate
